### ISSUE TITLE
Pgfutter exiting with no errors

### ISSUE THREAD

**Issue by baicunko** [lukasmartinelli/pgfutter#5]
I'm trying to import a ~1000 row CSV with 40 headers and PgFutter is able to find the headers and shows them but then it just exits, no table created, no error, nothing.
./pgfutter_linux_386 --username "TEST" --pw "TEST" --db "api" --schema "public"  --table "ola" csv hola.csv
delimiter in header column detected: LAT01;LON01;LAT02;LON02;LAT03;LON03;LAT04;LON04;LAT05;LON05;LAT06;LON06;LAT07;LON07;LAT08;LON08;LAT09;LON09;LAT10;LON10;LAT11;LON11;LAT12;LON12;LAT13;LON13;LAT14;LON14;LAT15;LON15;LAT16;LON16;LAT17;LON17;LAT18;LON18;LAT19;LON19;LAT20;LON20;LAT21;LON21;LAT22;LON22;LAT23;LON23;LAT24;LON24;LAT25;LON25;LAT26;LON26;LAT27;LON27;LAT28;LON28;LAT29;LON29;LAT30;LON30;LAT31;LON31;LAT32;LON32;LAT33;LON33;LAT34;LON34;LAT35;LON35;

**Comment by lukasmartinelli** [comment]
Sorry. The `delimiter in header column detected` is meant as error message.
The problem is that the delimiter is not specified with `--delimiter`.
With `pgfutter help csv` you see more flags you can set.

For your case `--delimiter ";"` should suffice. But I definitly need to make the error message better.
I also thought about automatically detecting the delimiter based on the header row - but this is a bit prone to errors.

**Comment by lukasmartinelli** [comment]
The error message is now improved in 89779952731fa65d6c9d6a2783ecaf3c3ca1b00b.
